INSERT INTO MPA (NAME) SELECT 'G'
WHERE NOT EXISTS (SELECT NAME FROM MPA WHERE NAME = 'G');

INSERT INTO MPA (NAME) SELECT 'PG'
WHERE NOT EXISTS (SELECT NAME FROM MPA WHERE NAME = 'PG');

INSERT INTO MPA (NAME) SELECT 'PG-13'
WHERE NOT EXISTS (SELECT NAME FROM MPA WHERE NAME = 'PG-13');

INSERT INTO MPA (NAME) SELECT 'R'
WHERE NOT EXISTS (SELECT NAME FROM MPA WHERE NAME = 'R');

INSERT INTO MPA (NAME) SELECT 'NC-17'
WHERE NOT EXISTS (SELECT NAME FROM MPA WHERE NAME = 'NC-17');

INSERT INTO GENRE (NAME) SELECT 'Комедия'
WHERE NOT EXISTS (SELECT NAME FROM GENRE WHERE NAME = 'Комедия');

INSERT INTO GENRE (NAME) SELECT 'Драма'
WHERE NOT EXISTS (SELECT NAME FROM GENRE WHERE NAME = 'Драма');

INSERT INTO GENRE (NAME) SELECT 'Мультфильм'
WHERE NOT EXISTS (SELECT NAME FROM GENRE WHERE NAME = 'Мультфильм');

INSERT INTO GENRE (NAME) SELECT 'Триллер'
WHERE NOT EXISTS (SELECT NAME FROM GENRE WHERE NAME = 'Триллер');

INSERT INTO GENRE (NAME) SELECT 'Документальный'
WHERE NOT EXISTS (SELECT NAME FROM GENRE WHERE NAME = 'Документальный');

INSERT INTO GENRE (NAME) SELECT 'Боевик'
WHERE NOT EXISTS (SELECT NAME FROM GENRE WHERE NAME = 'Боевик');